(function() {var implementors = {};
implementors["day01"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.usize.html\">usize</a>&gt; for <a class=\"struct\" href=\"day01/struct.Day01Entry.html\" title=\"struct day01::Day01Entry\">Day01Entry</a>",synthetic:false,types:["day01::Day01Entry"]},];
implementors["day06"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.HashMap.html\" title=\"struct std::collections::hash::map::HashMap\">HashMap</a>&lt;<a class=\"struct\" href=\"day06/struct.Orbiter.html\" title=\"struct day06::Orbiter\">Orbiter</a>&lt;'a&gt;, <a class=\"struct\" href=\"day06/struct.Orbiting.html\" title=\"struct day06::Orbiting\">Orbiting</a>&lt;'a&gt;, <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.RandomState.html\" title=\"struct std::collections::hash::map::RandomState\">RandomState</a>&gt;&gt; for <a class=\"struct\" href=\"day06/struct.Day06InverseMap.html\" title=\"struct day06::Day06InverseMap\">Day06InverseMap</a>&lt;'a&gt;",synthetic:false,types:["day06::Day06InverseMap"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.HashMap.html\" title=\"struct std::collections::hash::map::HashMap\">HashMap</a>&lt;<a class=\"struct\" href=\"day06/struct.Orbiting.html\" title=\"struct day06::Orbiting\">Orbiting</a>&lt;'a&gt;, <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html\" title=\"struct alloc::vec::Vec\">Vec</a>&lt;<a class=\"struct\" href=\"day06/struct.Orbiter.html\" title=\"struct day06::Orbiter\">Orbiter</a>&lt;'a&gt;&gt;, <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/collections/hash/map/struct.RandomState.html\" title=\"struct std::collections::hash::map::RandomState\">RandomState</a>&gt;&gt; for <a class=\"struct\" href=\"day06/struct.Day06Map.html\" title=\"struct day06::Day06Map\">Day06Map</a>&lt;'a&gt;",synthetic:false,types:["day06::Day06Map"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;&amp;'a <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"day06/struct.Orbiter.html\" title=\"struct day06::Orbiter\">Orbiter</a>&lt;'a&gt;",synthetic:false,types:["day06::Orbiter"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html\" title=\"trait core::convert::AsRef\">AsRef</a>&lt;&amp;'a <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for <a class=\"struct\" href=\"day06/struct.Orbiting.html\" title=\"struct day06::Orbiting\">Orbiting</a>&lt;'a&gt;",synthetic:false,types:["day06::Orbiting"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()