(function() {var implementors = {};
implementors["day01"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"day01/struct.Day01Entry.html\" title=\"struct day01::Day01Entry\">Day01Entry</a>",synthetic:false,types:["day01::Day01Entry"]},];
implementors["day06"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"day06/struct.Day06InverseMap.html\" title=\"struct day06::Day06InverseMap\">Day06InverseMap</a>&lt;'a&gt;",synthetic:false,types:["day06::Day06InverseMap"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"day06/struct.Day06Map.html\" title=\"struct day06::Day06Map\">Day06Map</a>&lt;'a&gt;",synthetic:false,types:["day06::Day06Map"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"day06/struct.Orbiter.html\" title=\"struct day06::Orbiter\">Orbiter</a>&lt;'a&gt;",synthetic:false,types:["day06::Orbiter"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/deref/trait.Deref.html\" title=\"trait core::ops::deref::Deref\">Deref</a> for <a class=\"struct\" href=\"day06/struct.Orbiting.html\" title=\"struct day06::Orbiting\">Orbiting</a>&lt;'a&gt;",synthetic:false,types:["day06::Orbiting"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()